package com.hyan.service;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ServiceHelloService service = new ServiceHelloService();
 * ServiceHello portType = service.getServiceHelloPort();
 * portType.getValue(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ServiceHelloService", targetNamespace = "http://service.hyan.com/", wsdlLocation = "http://localhost:9001/Service/ServiceHello?wsdl")
public class ServiceHelloService extends Service {

	private final static URL SERVICEHELLOSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.hyan.service.ServiceHelloService.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.hyan.service.ServiceHelloService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://localhost:9001/Service/ServiceHello?wsdl");
		} catch (MalformedURLException e) {
			logger.warning("Failed to create URL for the wsdl Location: 'http://localhost:9001/Service/ServiceHello?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		SERVICEHELLOSERVICE_WSDL_LOCATION = url;
	}

	public ServiceHelloService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ServiceHelloService() {
		super(SERVICEHELLOSERVICE_WSDL_LOCATION, new QName(
				"http://service.hyan.com/", "ServiceHelloService"));
	}

	/**
	 * 
	 * @return returns ServiceHello
	 */
	@WebEndpoint(name = "ServiceHelloPort")
	public ServiceHello getServiceHelloPort() {
		return super.getPort(new QName("http://service.hyan.com/",
				"ServiceHelloPort"), ServiceHello.class);
	}

}
